/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/components/display': RouteRecordInfo<'/components/display', '/components/display', Record<never, never>, Record<never, never>>,
    '/components/display/avatars': RouteRecordInfo<'/components/display/avatars', '/components/display/avatars', Record<never, never>, Record<never, never>>,
    '/components/display/collapse-description': RouteRecordInfo<'/components/display/collapse-description', '/components/display/collapse-description', Record<never, never>, Record<never, never>>,
    '/components/editors': RouteRecordInfo<'/components/editors', '/components/editors', Record<never, never>, Record<never, never>>,
    '/components/form': RouteRecordInfo<'/components/form', '/components/form', Record<never, never>, Record<never, never>>,
    '/components/form/': RouteRecordInfo<'/components/form/', '/components/form', Record<never, never>, Record<never, never>>,
    '/components/icon': RouteRecordInfo<'/components/icon', '/components/icon', Record<never, never>, Record<never, never>>,
    '/components/icon/ep-icon-list': RouteRecordInfo<'/components/icon/ep-icon-list', '/components/icon/ep-icon-list', Record<never, never>, Record<never, never>>,
    '/components/icon/ep-icon-picker': RouteRecordInfo<'/components/icon/ep-icon-picker', '/components/icon/ep-icon-picker', Record<never, never>, Record<never, never>>,
    '/components/notice': RouteRecordInfo<'/components/notice', '/components/notice', Record<never, never>, Record<never, never>>,
    '/components/notice/notice-message': RouteRecordInfo<'/components/notice/notice-message', '/components/notice/notice-message', Record<never, never>, Record<never, never>>,
    '/components/players': RouteRecordInfo<'/components/players', '/components/players', Record<never, never>, Record<never, never>>,
    '/components/players/audio': RouteRecordInfo<'/components/players/audio', '/components/players/audio', Record<never, never>, Record<never, never>>,
    '/components/players/video': RouteRecordInfo<'/components/players/video', '/components/players/video', Record<never, never>, Record<never, never>>,
    '/components/table': RouteRecordInfo<'/components/table', '/components/table', Record<never, never>, Record<never, never>>,
    '/components/table/': RouteRecordInfo<'/components/table/', '/components/table', Record<never, never>, Record<never, never>>,
    '/components/table/high': RouteRecordInfo<'/components/table/high', '/components/table/high', Record<never, never>, Record<never, never>>,
    '/components/table/Popover': RouteRecordInfo<'/components/table/Popover', '/components/table/Popover', Record<never, never>, Record<never, never>>,
    '/components/table/select': RouteRecordInfo<'/components/table/select', '/components/table/select', Record<never, never>, Record<never, never>>,
    '/directives': RouteRecordInfo<'/directives', '/directives', Record<never, never>, Record<never, never>>,
    '/directives/copy': RouteRecordInfo<'/directives/copy', '/directives/copy', Record<never, never>, Record<never, never>>,
    '/directives/debounce&throttle': RouteRecordInfo<'/directives/debounce&throttle', '/directives/debounce&throttle', Record<never, never>, Record<never, never>>,
    '/directives/draggable': RouteRecordInfo<'/directives/draggable', '/directives/draggable', Record<never, never>, Record<never, never>>,
    '/directives/flash': RouteRecordInfo<'/directives/flash', '/directives/flash', Record<never, never>, Record<never, never>>,
    '/directives/long-press': RouteRecordInfo<'/directives/long-press', '/directives/long-press', Record<never, never>, Record<never, never>>,
    '/directives/scrollText': RouteRecordInfo<'/directives/scrollText', '/directives/scrollText', Record<never, never>, Record<never, never>>,
    '/directives/watermark': RouteRecordInfo<'/directives/watermark', '/directives/watermark', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/menus': RouteRecordInfo<'/menus', '/menus', Record<never, never>, Record<never, never>>,
    '/menus/menu1': RouteRecordInfo<'/menus/menu1', '/menus/menu1', Record<never, never>, Record<never, never>>,
    '/menus/menu1/menu1-1': RouteRecordInfo<'/menus/menu1/menu1-1', '/menus/menu1/menu1-1', Record<never, never>, Record<never, never>>,
    '/menus/menu1/menu1-1/menu1-1-1': RouteRecordInfo<'/menus/menu1/menu1-1/menu1-1-1', '/menus/menu1/menu1-1/menu1-1-1', Record<never, never>, Record<never, never>>,
    '/menus/menu1/menu1-2': RouteRecordInfo<'/menus/menu1/menu1-2', '/menus/menu1/menu1-2', Record<never, never>, Record<never, never>>,
    '/menus/menu2': RouteRecordInfo<'/menus/menu2', '/menus/menu2', Record<never, never>, Record<never, never>>,
  }
}
